config/routes.rb
Rails.application.routes.draw do
  # change to orders#new down the line plz
  root 'orders#index'

  resources :orders do
    member do
      put 'ship'
      put 'complete'
    end
  end
  resources :types, only: %i(index show)

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '*path', to: 'orders#redirect_to_home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  VALID_COLORS = ['red', 'yellow', 'blue'].freeze

  attr_readonly :uuid

  belongs_to :type

  validates_presence_of :quantity, :color, :deliver_by, :type_id, :status
  validates_uniqueness_of :uuid
  validates :color, inclusion: { in: VALID_COLORS }
  validates :quantity, numericality: {
    greater_than: 0,
    only_integer: true
  }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, allow_blank: true
  validate :deliver_by_date_one_week_away
  validate :prevent_update_if_uuid_present

  before_create :assign_order_id

  aasm column: :status do
    state :pending, initial: true
    state :shipped
    state :completed

    event :ship do
      transitions from: :pending, to: :shipped
    end

    event :complete do
      transitions from: :shipped, to: :completed
    end
  end

  # add deliver_by error if date diff is less than 7
  def deliver_by_date_one_week_away
    return unless deliver_by.present?

    errors.add(
      :deliver_by,
      'is not at least 1 week away!'
    ) if ((deliver_by - Time.current)/1.day).round < 7
  end

  def assign_order_id
    self.uuid ||= SecureRandom.uuid
  end

  def prevent_update_if_uuid_present
    errors.add(
      :uuid,
      'cannot be updated!'
    ) if uuid_changed? && self.persisted?
  end
end

app/models/type.rb
class Type < ApplicationRecord
  VALID_WIDGET_TYPES = ['widget', 'widget pro', 'widget xtreme'].freeze

  has_many :orders

  validates_presence_of :name
  validates :name, inclusion: { in: VALID_WIDGET_TYPES }

  def offical_name
    name.split.map(&:capitalize)*' '
  end
end

app/models/user.rb
class User
  include ActiveModel::Model

  attr_accessor :username, :password

  def login_valid?
    username == ENV['ADMIN_USERNAME'] && password == ENV['ADMIN_PASSWORD']
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :ship, :complete, :destroy]
  before_action :check_for_admin, only: [:ship, :complete]
  before_action :check_if_pending, only: [:update]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all.includes(:type).order(quantity: :asc)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        OrderMailer.create_order(@order.id, @order.email).deliver if @order.email

        format.html { redirect_to @order, notice: "Order ID: #{@order.uuid} was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order ID: #{@order.uuid} was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def ship
    respond_to do |format|
      if @order.may_ship?
        @order.ship!
        format.html { redirect_to @order, notice: "Order ID: #{@order.uuid} was successfully shipped." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { redirect_to @order, notice: "Order cannot be shipped!" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def complete
    respond_to do |format|
      if @order.may_complete?
        @order.complete!
        format.html { redirect_to @order, notice: "Order ID: #{@order.uuid} was successfully completed." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { redirect_to @order, notice: "Order cannot be completed!" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_path, notice: "Order ID: #{@order.uuid} was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # redirect all malformed urls
  def redirect_to_home
    redirect_to(orders_path)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find_by(id: params[:id])
    redirect_to orders_path, notice: "Order ID: #{params[:id]} cannot be located." unless @order
  end

  def check_for_admin
    redirect_to @order, notice: "Only admins can do that!" unless session[:admin]
  end

  def check_if_pending
    redirect_to @order, notice: "You can't update a non-pending order!" unless @order.pending?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(
      :quantity,
      :color,
      :deliver_by,
      :type_id,
      :email
    ).reject { |_, v| v.blank? || v == [''] }
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:username, :password)

    @user = User.new({
      username: user_params[:username],
      password: user_params[:password]
    })

    if @user.login_valid?
      session[:admin] = true
      redirect_to orders_path, notice: 'Welcome Admin!'
    else
      @user.password = nil
      flash[:notice] = 'Sorry, invalid login.'
      render 'new'
    end
  end

  def destroy
    reset_session
    redirect_to orders_path, notice: 'Goodbye!'
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_type
    @type = Type.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def type_params
    params.require(:type).permit(
      :name
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WidgetOrderer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= simple_form_for @order do |f| %>
  <%= f.input :quantity, input_html: { min: 1 } %>
  <%= f.input :color, collection: Order::VALID_COLORS %>
  <%= f.input :deliver_by, as: :date,
    start_year: Date.today.year,
    order: [:month, :day, :year]
  %>
  <%= f.association :type, collection: Type.all %>
  <%= f.input :email, disabled: @order.persisted? %>
  <%= f.button :submit %>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>
<br>
<%= link_to 'Show Order', @order %>
<br>
<%= link_to 'All Orders', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<% if @orders %>
  <table>
    <thead>
      <tr>
        <th colspan="1">Quantity</th>
        <th colspan="1">Color</th>
        <th colspan="1">Type</th>
        <th colspan="1">Deliver By</th>
        <th colspan="1">Order ID</th>
        <th colspan="1">Status</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.quantity %></td>
          <td><%= order.color.capitalize %></td>
          <td><%= order.type.offical_name %></td>
          <td><%= order.deliver_by.strftime('%m/%d/%Y') %></td>
          <td><%= order.uuid %></td>
          <td><%= order.status.capitalize %></td>
          <td><%= link_to 'Show', order %></td>
          <td><%= link_to 'Edit', edit_order_path(order) %></td>
          <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>There are no orders present!</p>
<% end %>
<br>
<%= link_to 'New Order', new_order_path %>
<br>
<% if session[:admin] %>
  <%= link_to 'Log Out', logout_path, method: :delete %>
<% else %>
  <%= link_to 'Admin Login', login_path %>
<% end %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>
<br>
<%= link_to 'All Orders', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Order <%= @order.id %></h1>

<table>
  <thead>
    <tr>
      <th colspan="1">Quantity</th>
      <th colspan="1">Color</th>
      <th colspan="1">Type</th>
      <th colspan="1">Deliver By</th>
      <th colspan="1">Order ID</th>
      <th colspan="1">Status</th>
      <th colspan="3">Actions</th>
      <% if session[:admin] %>
        <th colspan="1">Change Status</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @order.quantity %></td>
      <td><%= @order.color.capitalize %></td>
      <td><%= @order.type.offical_name %></td>
      <td><%= @order.deliver_by.strftime('%m/%d/%Y') %></td>
      <td><%= @order.uuid %></td>
      <td><%= @order.status.capitalize %></td>
      <td><%= link_to 'Show', @order %></td>
      <td><%= link_to 'Edit', edit_order_path(@order) %></td>
      <td><%= link_to 'Destroy', @order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% if session[:admin] %>
        <% if @order.pending? %>
          <td><%= link_to 'Ship Order', ship_order_path(@order), method: :put %></td>
        <% elsif @order.shipped? %>
          <td><%= link_to 'Complete Order', complete_order_path(@order), method: :put %></td>
        <% else %>
          <td>All done! Hooray!</td>
        <% end %>
      <% end %>
    </tr>
  </tbody>
</table>
<br>
<%= link_to 'All Orders', orders_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Types</h1>

<table>
  <thead>
    <tr>
      <th colspan="1">Name</th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.offical_name %></td>
        <td><%= link_to 'Show', type %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Type <%= @type.id %></h1>

<p>
  <strong>Name:</strong>
  <%= @type.name.capitalize %>
</p>